### ISSUE TITLE
README doesn't mention openocd WORKSPACE requirements

### ISSUE THREAD

**Issue by bsirang** [silvergasp/bazel-embedded#33]
I had trouble getting openocd targets working initially until I dug deeper and realized I need to add this to the `WORKSPACE`

```
load("@bazel_embedded//tools/openocd:openocd_repository.bzl", "openocd_deps")

openocd_deps()
```

The README should mention it.

**Comment by silvergasp** [comment]
Hi bsirang. Thanks for rasing this. I've updated the readme as requested.
